export const templates = [
    { name: 'Dynamo', price: '$39', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'Infinite', price: '$49', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Fplugins%2F17-sZeQGQvWaZVikgMej4dLJBC83jpRQf&w=384&q=100' },
    { name: 'CSV Import', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F48049%2Fsmooth-2MVXUiOGCVsdLE5qj4qSwtknR5CC8G&w=384&q=100' },
    { name: 'Migrate', price: 'Paid', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Fplugins%2F14-q5cgI7ekkk8vu0RtbwfReX473glohy&w=384&q=100' },
    { name: 'Fuselle', price: '$49', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Fplugins%2F249-j2uI6nZJjQdj9ahkU6zJmUWcZTPlLT&w=384&q=100' },
    { name: 'Smooth', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F48049%2Fsmooth-2MVXUiOGCVsdLE5qj4qSwtknR5CC8G&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { name: 'Google Sheets', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45421%2Ffuselle-tcCHMvlWdyuHMsc1zCNug6Kxqfa82d&w=384&q=100' }
  ];

  export const templatesData = [
    {id:"1", name: 'Dynamo', price: '$39', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    {id:"2", name: 'Infinite', price: '$49', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Fplugins%2F17-sZeQGQvWaZVikgMej4dLJBC83jpRQf&w=384&q=100' },
    { id:"3",name: 'CSV Import', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F48049%2Fsmooth-2MVXUiOGCVsdLE5qj4qSwtknR5CC8G&w=384&q=100' },
    {id:"4", name: 'Migrate', price: 'Paid', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Fplugins%2F14-q5cgI7ekkk8vu0RtbwfReX473glohy&w=384&q=100' },
    {id:"5", name: 'Fuselle', price: '$49', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Fplugins%2F249-j2uI6nZJjQdj9ahkU6zJmUWcZTPlLT&w=384&q=100' },
    {id:"6", name: 'Smooth', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F48049%2Fsmooth-2MVXUiOGCVsdLE5qj4qSwtknR5CC8G&w=384&q=100' },
    {id:"7", name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    {id:"8", name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    { id:"9",name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
    {id:"10", name: 'CMS Export', price: 'Free', image: 'https://www.framer.com/creators-assets/_next/image/?url=https%3A%2F%2Fy4pdgnepgswqffpt.public.blob.vercel-storage.com%2Ftemplates%2F45721%2Finfinite-framer-agency-template-7VBC8HjWtlgvQU0znJBljTiQdIz60p&w=384&q=100' },
  
  ];